# Generated by Django 5.0.1 on 2024-03-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
