# Generated by Django 5.0.1 on 2024-03-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_username_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
