# Generated by Django 4.2.1 on 2023-11-04 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('joke', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=30)),
                ('from_user', models.CharField(max_length=40)),
            ],
        ),
    ]
