# Generated by Django 4.2.1 on 2023-11-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jokes',
            new_name='Joke',
        ),
    ]
