# Generated by Django 4.2.7 on 2023-11-29 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_jokes_joke'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sended_on', models.DateField(default=datetime.date.today)),
                ('header', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=400)),
                ('for_user', models.CharField(max_length=40)),
            ],
        ),
    ]
