# Generated by Django 4.2.7 on 2023-12-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_notifications_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sended_on',
            field=models.DateField(default='02.12.2023, 23:40'),
        ),
    ]
