# Generated by Django 4.2.7 on 2023-12-13 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_notification_sended_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sended_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
