# Generated by Django 5.0.1 on 2024-01-19 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_notification_sended_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedJoke',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('ReportCategory', models.CharField(max_length=30)),
                ('ReportTextField', models.CharField(max_length=120)),
                ('joke', models.CharField(max_length=300)),
                ('from_user', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='joke',
            name='from_user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='joke',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
