# Generated by Django 5.0.1 on 2024-01-19 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_reportedjoke_alter_joke_from_user_alter_joke_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedjoke',
            name='joke_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='joke',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='joke',
            name='from_user',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='ReportCategory',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='ReportTextField',
            field=models.CharField(editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='from_user',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='joke',
            field=models.CharField(editable=False, max_length=300),
        ),
    ]
