# Generated by Django 5.0.1 on 2024-01-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_reportedjoke_joke_id_alter_joke_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedjoke',
            name='joke_id',
            field=models.CharField(editable=False, max_length=80),
        ),
    ]
