# Generated by Django 5.0.1 on 2024-01-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_reportedjoke_joke_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedjoke',
            name='id',
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='joke_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
