# Generated by Django 5.0.1 on 2024-01-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_reportedjoke_id_alter_reportedjoke_joke_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedjoke',
            name='id',
            field=models.IntegerField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='joke_id',
            field=models.UUIDField(editable=False),
        ),
    ]
