# Generated by Django 5.0.1 on 2024-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_reportedjoke_id_alter_reportedjoke_joke_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedjoke',
            name='times_reported',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='ReportTextField',
            field=models.CharField(default='None', editable=False, max_length=120),
        ),
    ]
