# Generated by Django 5.0.1 on 2024-03-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_reportedjoke_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='from_user',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='joke',
            name='joke',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='ReportTextField',
            field=models.CharField(default='None', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='from_user',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='joke',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
