# Generated by Django 5.0.1 on 2024-03-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_joke_from_user_alter_joke_joke_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='for_user',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
