# Generated by Django 5.0.1 on 2024-03-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_notification_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='for_user',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
