# Generated by Django 5.0.1 on 2024-03-13 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_notification_for_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedjoke',
            name='id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='sended_on',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='joke_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
