# Generated by Django 5.0.1 on 2024-03-14 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_reportedjoke_id_alter_notification_sended_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedjoke',
            name='times_reported',
        ),
        migrations.AddField(
            model_name='reportedjoke',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportedjoke',
            name='joke_id',
            field=models.UUIDField(editable=False),
        ),
    ]
