# Generated by Django 5.0.1 on 2024-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_reportedjoke_times_reported_reportedjoke_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='from_user',
            field=models.CharField(max_length=20),
        ),
    ]
