# Generated by Django 5.0.1 on 2024-03-22 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_joke_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sended_on',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
